#!/usr/bin/env python

import json
import args
import urllib
import urllib2

pp = args.args()
res = []

url = "%s?%s" % (pp.host, urllib.urlencode({"s": " ".join(pp.keys)}))
req = urllib2.Request(url)
response = urllib2.urlopen(req)
data = json.loads(response.read(), encoding="UTF-8")
res.append(data)
    
print json.dumps(data, indent=4, encoding="UTF-8", ensure_ascii=False)