#!/usr/bin/env python

import json
import urllib
import urllib2
import args

pp = args.args()
res = {}

for k in pp.keys:
    req = urllib2.Request(pp.host, urllib.urlencode({"key": k}))
    response = urllib2.urlopen(req)
    data = json.loads(response.read())
    res.update(data)

print json.dumps(res, indent=4)
